namespace Quantum
{
    using UnityEngine;

    // Base for the "Passive Upgrade" level-up pool kind - see docs/level-up-upgrades.md. Icon/
    // DisplayName come from UpgradeData (no Rarity - see UpgradeData's own comment); this adds a
    // virtual Apply, same shape as
    // GlobalUpgradeData.Apply(Frame, EntityRef) - each concrete effect (e.g. a hero's own passive
    // ascension) is its own subtype rather than a switch here, and reads whatever hero-specific
    // component it needs off the entity itself.
    public abstract partial class PassiveUpgradeData : UpgradeData, IRankedUpgrade
    {
        [TextArea(2, 4)]
        public string Description;

        // 1 (default) = classic single-pick, unchanged behavior for every existing passive across
        // every hero. >1 makes this a ranked Ascension line - PassiveUpgradeUtility.Grant then calls
        // the rank-aware Apply overload below instead, and PassiveUpgradeUtility.IsAlreadyPicked stops
        // excluding it from the draft pool until this many picks have landed. See
        // docs/level-up-upgrades.md for the full mechanism.
        //
        // An auto-property (not a plain field) specifically so this satisfies IRankedUpgrade.MaxRank
        // (a get-only interface property - a field can never implement an interface property member,
        // even though field/property access look identical at every call site). [field: SerializeField]
        // is what makes Unity still serialize/show it in the Inspector exactly like a plain field would.
        [field: SerializeField]
        public byte MaxRank { get; set; } = 1;

        // Kept virtual (not abstract) rather than removed so every existing non-ranked subclass across
        // every hero compiles with zero changes - only ranked ascensions need to override the rank-
        // aware overload below instead.
        public virtual void Apply(Frame f, EntityRef entity) { }

        // Generic prerequisite gate, checked by LevelUpUtility's candidate-collection methods
        // alongside the existing rank/already-picked filters - default true, so every existing
        // upgrade across every hero is offered exactly as before. A concrete override lets an
        // Ascension require some other upgrade/tag first (e.g. Max's Flashpoint checking for a real
        // Burn source via CanApplyBurn) without a hero-specific branch anywhere in LevelUpUtility
        // itself - reusable by any future hero's own prerequisite-gated pick.
        public virtual bool IsEligible(Frame f, EntityRef entity) => true;

        // Ranked ascensions override this instead of the parameterless Apply above. `rank` is the
        // rank being granted by this pick (1-based) - implementations should SET their component's
        // fields to that rank's total tuned values, not add to whatever the previous rank left behind,
        // since every rank's numbers are cumulative totals (e.g. "+60% damage" at rank 2 is the total,
        // not +30% stacked on top of rank 1's +30%).
        public virtual void Apply(Frame f, EntityRef entity, int rank) => Apply(f, entity);

        public override string GetDescription() => Description;

        // Ranked ascensions author their per-rank flavor text directly here (rank 1 = index 0) -
        // real data, editable per-rank in the Inspector, rather than generated by string-interpolating
        // the tuned numbers in a GetDescription(int rank) override. Falls back to the plain
        // Description above if empty/unauthored/out of range, so a non-ranked upgrade (MaxRank == 1)
        // or one that hasn't authored per-rank text yet still works unchanged.
        [TextArea(2, 4)]
        public string[] RankDescriptions;

        // Shown on the level-up card for the specific rank being offered (see
        // GameplayUiController.BuildCardData). Virtual so a ranked ascension that genuinely needs
        // live-computed text (rather than authored data) can still override this directly.
        public virtual string GetDescription(int rank)
        {
            int index = rank - 1;

            if (RankDescriptions != null && index >= 0 && index < RankDescriptions.Length
                && string.IsNullOrEmpty(RankDescriptions[index]) == false)
                return RankDescriptions[index];

            return GetDescription();
        }
    }
}
