// Borderlands-style variant of Project/Mobile Toon Modular Level.
//
// Keeps every input convention of the original so the exact same converter output
// (ModularLevelConverterWindow) drops straight in:
//   TEXCOORD0 (mesh.uv)   wall / surface albedo
//   TEXCOORD1 (mesh.uv2)  lightmap, generated by the converter
//   TEXCOORD2 (mesh.uv3)  style mask atlas - R = baked crease ink core, G = core + outer fade
//   TEXCOORD3 (mesh.uv4)  optional smoothed object-space normal for the inverted-hull outline.
//                         SmoothNormalBakerWindow writes it; the pass falls back to NORMAL when
//                         the channel is absent, so an unbaked mesh still renders.
//   COLOR.r               0 = wall role, 1 = surface role
//   COLOR.g               baked vertex AO
//
// What it adds on top of the original's flat toon band:
//   * hard multi-step cel banding with a light-wrap term, so the two-tone reads even on the
//     Mobile RP asset where main-light shadows are switched off entirely
//   * an optional ramp texture for hand-authored shadow colour
//   * hard-edged toon specular
//   * a dark interior rim ink, the contour Borderlands draws on curvature rather than silhouette
//   * screen-space cross-hatching confined to the shadow bands (off by default)
//   * an inverted-hull ink outline pass, the actual Borderlands silhouette technique
//
// The baked crease ink from the style atlas is preserved and split between a lit and an unlit
// contribution (_InkUnlit), because Borderlands ink sits on top of shading rather than under it.
Shader "Project/Borderlands Toon Modular Level"
{
    Properties
    {
        [Header(Textures)]
        [MainTexture] _WallMap ("Wall Texture", 2D) = "white" {}
        _SurfaceMap ("Surface Texture", 2D) = "white" {}
        [Toggle] _SurfaceUseWorldUV ("Surface World UV", Float) = 0
        [NoScaleOffset] _StyleMask ("Outline and Surface Fade Atlas", 2D) = "white" {}

        [Header(Surface World Noise)]
        [NoScaleOffset] _GlobalNoiseMap ("Surface Noise Texture", 2D) = "gray" {}
        _GlobalNoiseScale ("Noise Scale", Float) = 0.2
        _GlobalNoiseStrength ("Noise Strength", Range(0,1)) = 0.15
        _GlobalNoiseDarkColor ("Noise Dark Color", Color) = (0.72,0.75,0.78,1)
        _GlobalNoiseLightColor ("Noise Light Color", Color) = (1,1,1,1)
        _GlobalNoiseOffset ("Noise World Offset", Vector) = (0,0,0,0)

        [Header(Wall)]
        _WallColor ("Wall Color", Color) = (1,1,1,1)
        _InkColor ("Ink Color", Color) = (0.025,0.02,0.03,1)
        _WallOuterGlowStrength ("Ink Outer Fade", Range(0,1)) = 0.3
        _InkUnlit ("Ink Unlit Amount", Range(0,1)) = 0.75

        [Header(World Height Wall Line)]
        _WallLineColor ("Line Color", Color) = (0.025,0.02,0.03,1)
        _WallLineY ("World Y", Float) = 0
        _WallLineThickness ("Thickness", Float) = 0.1
        _WallLineStrength ("Strength", Range(0,1)) = 0

        [Header(Surface)]
        _SurfaceColor ("Surface Color", Color) = (1,1,1,1)
        _SurfaceEdgeColor ("Surface Fade Color", Color) = (0.22,0.16,0.1,0.55)

        [Header(Cel Shading)]
        _CelSteps ("Bands", Range(1,6)) = 2
        _CelSharpness ("Band Hardness", Range(0,1)) = 0.9
        _CelWrap ("Light Wrap", Range(0,1)) = 0.25
        _CelShadowColor ("Shadow Color", Color) = (0.38,0.42,0.55,1)
        _CelMidColor ("Mid Color", Color) = (0.72,0.74,0.8,1)
        _CelGiStrength ("Ambient Strength", Range(0,2)) = 1
        [Toggle] _UseCelRamp ("Use Ramp Texture", Float) = 0
        [NoScaleOffset] _CelRamp ("Cel Ramp (L to R)", 2D) = "white" {}

        [Header(Toon Specular)]
        _ToonSpecColor ("Specular Color", Color) = (1,1,1,1)
        _ToonSpecPower ("Specular Power", Float) = 48
        _ToonSpecThreshold ("Specular Threshold", Range(0,1)) = 0.5
        _ToonSpecSoftness ("Specular Softness", Range(0.001,0.5)) = 0.02
        _ToonSpecStrength ("Specular Strength", Range(0,2)) = 0

        [Header(Rim Ink)]
        _RimInkColor ("Rim Ink Color", Color) = (0.025,0.02,0.03,1)
        _RimInkPower ("Rim Ink Power", Range(0.5,12)) = 4
        _RimInkStrength ("Rim Ink Strength", Range(0,1)) = 0

        [Header(Ink Hatching)]
        [NoScaleOffset] _HatchMap ("Hatch Texture", 2D) = "white" {}
        _HatchScale ("Hatch Tiling (per world unit)", Float) = 0.5
        _HatchStrength ("Hatch Strength", Range(0,1)) = 0
        _HatchShadowStart ("Hatch Shadow Start", Range(0,1)) = 0
        _HatchShadowEnd ("Hatch Shadow End", Range(0,1)) = 0.6

        [Header(Ink Outline)]
        _OutlineColor ("Outline Color", Color) = (0.02,0.02,0.03,1)
        _OutlineWidth ("Outline Width (world)", Float) = 0.035
        _OutlineMinPixels ("Outline Min (px)", Float) = 1
        _OutlineMaxPixels ("Outline Max (px)", Float) = 6
        [Toggle] _OutlineUseSmoothNormals ("Use Baked Smooth Normals (UV4)", Float) = 0

        [Header(Height Fog)]
        _HeightFogColor ("Height Fog Color", Color) = (0.55,0.62,0.7,1)
        _HeightFogTopY ("Height Fog Top Y", Float) = 0
        _HeightFogFalloff ("Height Fog Falloff", Float) = 4
        _HeightFogStrength ("Height Fog Strength", Range(0,1)) = 0

        [Header(Base Height Gradient)]
        _GradientBottomColor ("Gradient Bottom", Color) = (0.65,0.72,0.68,1)
        _GradientTopColor ("Gradient Top", Color) = (1,1,1,1)
        _GradientStartY ("Gradient Start Y", Float) = 0
        _GradientDistance ("Gradient Distance", Float) = 4
        _GradientStrength ("Gradient Strength", Range(0,1)) = 1

        // Stable implementation settings.
        [HideInInspector] _BaseColor ("Global Base Tint", Color) = (1,1,1,1)
        [HideInInspector] _AOColor ("Vertex AO Color", Color) = (0.25,0.28,0.35,1)
        [HideInInspector] _WallAOStrength ("Wall Vertex AO Strength", Range(0,1)) = 0.45
        [HideInInspector] _SurfaceAOStrength ("Surface Vertex AO Strength", Range(0,1)) = 0
        [HideInInspector] _AOContrast ("Vertex AO Contrast", Range(0.25,4)) = 1
    }

    SubShader
    {
        Tags { "RenderType"="Opaque" "RenderPipeline"="UniversalPipeline" "Queue"="Geometry" }

        // Inverted hull. URP's DrawObjects pass renders SRPDefaultUnlit alongside
        // UniversalForward, so this draws for the same material without a renderer feature -
        // which matters because Mobile_Renderer has no feature list at all and therefore no
        // screen-space CartoonOutline to fall back on.
        Pass
        {
            Name "InkOutline"
            Tags { "LightMode"="SRPDefaultUnlit" }
            Cull Front
            ZWrite On
            ZTest LEqual
            HLSLPROGRAM
            #pragma target 3.0
            #pragma vertex OutlineVertex
            #pragma fragment OutlineFragment
            #pragma multi_compile_fog
            #pragma multi_compile_instancing
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
            #include "BorderlandsToonModularLevelInput.hlsl"

            struct OutlineAttributes
            {
                float4 positionOS : POSITION;
                float3 normalOS : NORMAL;
                float3 smoothNormalOS : TEXCOORD3;
                UNITY_VERTEX_INPUT_INSTANCE_ID
            };
            struct OutlineVaryings { float4 positionCS : SV_POSITION; half fog : TEXCOORD0; };

            OutlineVaryings OutlineVertex(OutlineAttributes i)
            {
                UNITY_SETUP_INSTANCE_ID(i);
                OutlineVaryings o = (OutlineVaryings)0;

                // A merged modular mesh splits vertices at every hard edge, so extruding along
                // NORMAL tears the hull apart at each corner. The baked channel closes it; the
                // lerp keeps the shader usable on meshes that were never baked.
                float3 extrudeOS = lerp(i.normalOS, i.smoothNormalOS, saturate(_OutlineUseSmoothNormals));
                if (dot(extrudeOS, extrudeOS) < 1e-8)
                    extrudeOS = i.normalOS;

                float3 positionWS = TransformObjectToWorld(i.positionOS.xyz);
                float3 normalWS = normalize(TransformObjectToWorldNormal(extrudeOS));
                float4 positionCS = TransformWorldToHClip(positionWS);

                // Thickness in pixels, from a world-space width.
                //
                // P._m11 is 1/tan(fov/2), the world-to-NDC-y scale at unit depth. Dividing by w
                // alone would drop it and, at this project's 14 degree telephoto FOV, draw the
                // outline roughly eight times thinner than _OutlineWidth asks for. The same term
                // is 1/orthographicSize under an orthographic camera, where w is 1, so the
                // formula stays correct if the view is ever switched.
                float2 screenSize = max(_ScreenParams.xy, 1.0);
                float ndcYToPixels = screenSize.y * 0.5;
                float widthPixels = _OutlineWidth * abs(UNITY_MATRIX_P._m11) / max(positionCS.w, 1e-4) * ndcYToPixels;
                widthPixels = clamp(widthPixels, _OutlineMinPixels, _OutlineMaxPixels);

                // Aspect-correct the extrusion direction BEFORE normalising it. Normalising in
                // raw clip space and rescaling afterwards would skew the direction on any
                // non-square viewport, thinning the line along one diagonal.
                float3 normalCS = mul((float3x3)UNITY_MATRIX_VP, normalWS);
                float2 direction = normalCS.xy * screenSize;
                direction /= max(length(direction), 1e-5);

                positionCS.xy += direction * widthPixels * (2.0 / screenSize) * positionCS.w;

                o.positionCS = positionCS;
                o.fog = ComputeFogFactor(positionCS.z);
                return o;
            }

            half4 OutlineFragment(OutlineVaryings i) : SV_Target
            {
                return half4(MixFog(_OutlineColor.rgb, i.fog), 1);
            }
            ENDHLSL
        }

        Pass
        {
            Name "ForwardLit"
            Tags { "LightMode"="UniversalForward" }
            HLSLPROGRAM
            #pragma target 3.0
            #pragma vertex Vert
            #pragma fragment Frag
            #pragma multi_compile _ _MAIN_LIGHT_SHADOWS
            #pragma multi_compile _ _MAIN_LIGHT_SHADOWS_CASCADE
            #pragma multi_compile _ _MAIN_LIGHT_SHADOWS_SCREEN
            #pragma multi_compile_fragment _ _SHADOWS_SOFT
            #pragma multi_compile _ LIGHTMAP_ON
            #pragma multi_compile_fog
            #pragma multi_compile_instancing
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl"
            #include "BorderlandsToonModularLevelInput.hlsl"

            TEXTURE2D(_WallMap); SAMPLER(sampler_WallMap);
            TEXTURE2D(_SurfaceMap); SAMPLER(sampler_SurfaceMap);
            TEXTURE2D(_StyleMask); SAMPLER(sampler_StyleMask);
            TEXTURE2D(_GlobalNoiseMap);
            TEXTURE2D(_CelRamp);
            TEXTURE2D(_HatchMap);

            half SampleGlobalNoiseFBM(float2 baseUv)
            {
                half n = SAMPLE_TEXTURE2D(_GlobalNoiseMap, sampler_LinearRepeat, baseUv).r;
                n += SAMPLE_TEXTURE2D(_GlobalNoiseMap, sampler_LinearRepeat, baseUv * 2.63 + 0.37).r * 0.5;
                return n / 1.5;
            }

            struct A
            {
                float4 positionOS:POSITION; half3 normalOS:NORMAL;
                float2 uv:TEXCOORD0; float2 uv2:TEXCOORD1; float2 uv3:TEXCOORD2;
                half4 color:COLOR; UNITY_VERTEX_INPUT_INSTANCE_ID
            };
            struct V
            {
                float4 positionCS:SV_POSITION; float3 positionWS:TEXCOORD0; half3 normalWS:TEXCOORD1;
                float2 uv:TEXCOORD2; float2 uv3:TEXCOORD3; half2 roleAo:TEXCOORD4;
                DECLARE_LIGHTMAP_OR_SH(lightmapUV,vertexSH,5); half fog:TEXCOORD6;
            };

            V Vert(A i)
            {
                V o=(V)0;
                UNITY_SETUP_INSTANCE_ID(i);
                o.normalWS=TransformObjectToWorldNormal(i.normalOS);
                o.positionWS=TransformObjectToWorld(i.positionOS.xyz);
                o.positionCS=TransformWorldToHClip(o.positionWS);
                o.uv=i.uv; o.uv3=i.uv3; o.roleAo=i.color.rg;
                OUTPUT_LIGHTMAP_UV(i.uv2,unity_LightmapST,o.lightmapUV);
                OUTPUT_SH(o.normalWS,o.vertexSH);
                o.fog=ComputeFogFactor(o.positionCS.z);
                return o;
            }

            half4 Frag(V i):SV_Target
            {
                half surface=step(0.5h,i.roleAo.x);
                half3 wall=SAMPLE_TEXTURE2D(_WallMap,sampler_WallMap,TRANSFORM_TEX(i.uv,_WallMap)).rgb;
                // World mode makes the surface texture continuous across every modular piece.
                float2 surfaceLocalUv=TRANSFORM_TEX(i.uv,_SurfaceMap);
                float2 surfaceWorldUv=i.positionWS.xz*_SurfaceMap_ST.xy+_SurfaceMap_ST.zw;
                float2 surfaceUv=lerp(surfaceLocalUv,surfaceWorldUv,saturate(_SurfaceUseWorldUV));
                half3 top=SAMPLE_TEXTURE2D(_SurfaceMap,sampler_SurfaceMap,surfaceUv).rgb;
                half3 materialColor=lerp(_WallColor.rgb,_SurfaceColor.rgb,surface);
                half3 baseColor=lerp(wall,top,surface)*materialColor*_BaseColor.rgb;

                // surface is a hard 0/1 (step()), so walls never see this tint - skip the
                // sampling there entirely instead of paying for it and discarding the result.
                [branch] if (surface > 0.5h)
                {
                    float3 noisePosition=i.positionWS+_GlobalNoiseOffset.xyz;
                    float2 noiseUv=noisePosition.xz*_GlobalNoiseScale;
                    half globalNoise=SampleGlobalNoiseFBM(noiseUv);
                    half3 noiseTint=lerp(_GlobalNoiseDarkColor.rgb,_GlobalNoiseLightColor.rgb,globalNoise);
                    baseColor*=lerp(half3(1,1,1),noiseTint,_GlobalNoiseStrength);
                }

                half vertexAO=pow(saturate(i.roleAo.y),max(_AOContrast,0.01h));
                half3 aoTint=lerp(_AOColor.rgb,half3(1,1,1),vertexAO);
                half aoStrength=lerp(_WallAOStrength,_SurfaceAOStrength,surface);
                baseColor*=lerp(half3(1,1,1),aoTint,aoStrength);

                float t=saturate((i.positionWS.y-_GradientStartY)/max(abs(_GradientDistance),0.0001));
                baseColor*=lerp(half3(1,1,1),lerp(_GradientBottomColor.rgb,_GradientTopColor.rgb,t),_GradientStrength);

                // Draw one continuous, pixel-stable band across wall-role geometry only.
                float lineDistance=abs(i.positionWS.y-_WallLineY);
                float lineHalfThickness=max(_WallLineThickness*0.5,0.0);
                float lineAntiAlias=max(fwidth(i.positionWS.y),0.0001);
                half wallLineMask=(1-surface)*(1-smoothstep(lineHalfThickness,lineHalfThickness+lineAntiAlias,lineDistance));
                wallLineMask*=saturate(_WallLineStrength)*_WallLineColor.a;
                baseColor=lerp(baseColor,_WallLineColor.rgb,wallLineMask);

                half2 styleMask=SAMPLE_TEXTURE2D(_StyleMask,sampler_StyleMask,i.uv3).rg;
                half amount=saturate(1-styleMask.r);
                half roleAlpha=lerp(_InkColor.a,_SurfaceEdgeColor.a,surface);
                half3 creaseInkColor=lerp(_InkColor.rgb,_SurfaceEdgeColor.rgb,surface);
                // Wall tiles pack their baked outer fade in green. Old grayscale atlases remain
                // compatible because red and green are equal and therefore produce no halo.
                half glowEnvelope=saturate(1-styleMask.g);
                half wallOuterGlow=saturate(glowEnvelope-amount)*(1-surface);
                baseColor*=1-saturate(wallOuterGlow*_WallOuterGlowStrength);

                // Split between a lit and an unlit share. Borderlands ink reads as drawn on top
                // of the shading rather than as a dark albedo the light then brightens back up.
                half inkAmount=amount*roleAlpha;
                half unlitInk=inkAmount*saturate(_InkUnlit);
                baseColor=lerp(baseColor,creaseInkColor,inkAmount-unlitInk);

                half3 n=normalize(i.normalWS);
                half3 viewDirWS=GetWorldSpaceNormalizeViewDir(i.positionWS);
                Light light=GetMainLight(TransformWorldToShadowCoord(i.positionWS));

                // Wrapping keeps a readable mid band on the Mobile RP asset, which ships with
                // main-light shadows disabled, so raw N.L is the only shaping term available.
                half wrap=saturate(_CelWrap);
                half ndl=saturate((dot(n,light.direction)+wrap)/(1+wrap));
                half cel=CelQuantize(ndl*light.shadowAttenuation);

                // Two segments, shadow -> mid -> light, so a 3-band setup gets a real mid tone
                // instead of a straight lerp between the two extremes.
                half3 litColor=light.color;
                half3 ramp=lerp(lerp(_CelShadowColor.rgb,_CelMidColor.rgb,saturate(cel*2)),
                                lerp(_CelMidColor.rgb,litColor,saturate(cel*2-1)),
                                step(0.5h,cel));
                // Uniform condition, so this branch is fully coherent and costs nothing - it just
                // keeps the extra sampler fetch off the default (ramp-less) mobile path.
                [branch] if (_UseCelRamp > 0.5h)
                    ramp=SAMPLE_TEXTURE2D(_CelRamp,sampler_LinearClamp,float2(cel,0.5)).rgb*litColor;

                half3 gi=SAMPLE_GI(i.lightmapUV,i.vertexSH,n)*_CelGiStrength;
                half3 color=baseColor*(ramp+gi);

                // Hard-edged highlight. Gated by cel so it can never appear inside a shadow band.
                [branch] if (_ToonSpecStrength > 0.001h)
                {
                    half3 halfVector=SafeNormalize(light.direction+viewDirWS);
                    half specular=pow(saturate(dot(n,halfVector)),max(_ToonSpecPower,1));
                    specular=smoothstep(_ToonSpecThreshold,_ToonSpecThreshold+_ToonSpecSoftness,specular);
                    color+=_ToonSpecColor.rgb*(specular*_ToonSpecStrength*cel*light.shadowAttenuation);
                }

                // Interior contour on curvature. Off by default, and deliberately so on this
                // geometry: a rim term only reads as a contour where the normal turns across the
                // surface. Modular level pieces are flat facets, so dot(n, view) is near-constant
                // over a whole wall face and this tints the entire face rather than its edge -
                // and because the term is view-dependent, that tint then slides as the camera
                // moves. Raise it only on genuinely curved props.
                [branch] if (_RimInkStrength > 0.001h)
                {
                    half rim=pow(saturate(1-saturate(dot(n,viewDirWS))),max(_RimInkPower,0.01h));
                    color=lerp(color,_RimInkColor.rgb,saturate(rim*_RimInkStrength*_RimInkColor.a));
                }

                // Cross-hatch, restricted to the darker bands. Projected in WORLD space, the same
                // way the surface noise above already is: sampling it in screen space pins the
                // pattern to the display and makes the level slide underneath it as the camera
                // moves. (That shower-door look is genuinely what printed comics do - ink sits on
                // the page, not on the scene - but it reads as a bug in a game that pans.)
                //
                // One sample, no triplanar. The surface role is flat so it takes a plain XZ
                // projection; walls pick whichever vertical plane their normal faces most, which
                // is exact for the axis-aligned modular pieces this shader ships on and only
                // shears on geometry rotated off-axis.
                [branch] if (_HatchStrength > 0.001h)
                {
                    float2 wallUv=abs(n.x)>abs(n.z) ? i.positionWS.zy : i.positionWS.xy;
                    float2 hatchUv=lerp(wallUv,i.positionWS.xz,surface)*_HatchScale;
                    half hatch=SAMPLE_TEXTURE2D(_HatchMap,sampler_LinearRepeat,hatchUv).r;
                    half hatchMask=1-smoothstep(_HatchShadowStart,max(_HatchShadowEnd,_HatchShadowStart+0.001h),cel);
                    color*=lerp(1,hatch,hatchMask*_HatchStrength);
                }

                color=lerp(color,creaseInkColor,unlitInk);

                float heightFogDepth=max(_HeightFogTopY-i.positionWS.y,0);
                float heightFogFalloffSq=max(_HeightFogFalloff*_HeightFogFalloff,0.0001);
                half heightFog=1-exp(-(heightFogDepth*heightFogDepth)/heightFogFalloffSq);
                heightFog*=saturate(_HeightFogStrength*_HeightFogColor.a);
                color=lerp(color,_HeightFogColor.rgb,heightFog);
                return half4(MixFog(color,i.fog),1);
            }
            ENDHLSL
        }

        Pass
        {
            Name "ShadowCaster"
            Tags { "LightMode"="ShadowCaster" }
            ZWrite On ZTest LEqual ColorMask 0 Cull Back
            HLSLPROGRAM
            #pragma target 3.0
            #pragma vertex ShadowVertex
            #pragma fragment ShadowFragment
            #pragma multi_compile_instancing
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Shadows.hlsl"
            #include "BorderlandsToonModularLevelInput.hlsl"

            float3 _LightDirection;
            struct ShadowAttributes { float4 positionOS:POSITION; float3 normalOS:NORMAL; UNITY_VERTEX_INPUT_INSTANCE_ID };
            struct ShadowVaryings { float4 positionCS:SV_POSITION; };
            ShadowVaryings ShadowVertex(ShadowAttributes i)
            {
                UNITY_SETUP_INSTANCE_ID(i);
                ShadowVaryings o;
                float3 positionWS=TransformObjectToWorld(i.positionOS.xyz);
                float3 normalWS=TransformObjectToWorldNormal(i.normalOS);
                o.positionCS=TransformWorldToHClip(ApplyShadowBias(positionWS,normalWS,_LightDirection));
                #if UNITY_REVERSED_Z
                    o.positionCS.z=min(o.positionCS.z,o.positionCS.w*UNITY_NEAR_CLIP_VALUE);
                #else
                    o.positionCS.z=max(o.positionCS.z,o.positionCS.w*UNITY_NEAR_CLIP_VALUE);
                #endif
                return o;
            }
            half4 ShadowFragment(ShadowVaryings i):SV_Target { return 0; }
            ENDHLSL
        }

        Pass
        {
            Name "DepthOnly"
            Tags { "LightMode"="DepthOnly" }
            ZWrite On ZTest LEqual ColorMask 0 Cull Back
            HLSLPROGRAM
            #pragma target 3.0
            #pragma vertex DepthVertex
            #pragma fragment DepthFragment
            #pragma multi_compile_instancing
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
            #include "BorderlandsToonModularLevelInput.hlsl"
            struct DepthAttributes { float4 positionOS:POSITION; float3 normalOS:NORMAL; UNITY_VERTEX_INPUT_INSTANCE_ID };
            struct DepthVaryings { float4 positionCS:SV_POSITION; };
            DepthVaryings DepthVertex(DepthAttributes i) { UNITY_SETUP_INSTANCE_ID(i); DepthVaryings o; o.positionCS=TransformObjectToHClip(i.positionOS.xyz); return o; }
            half4 DepthFragment(DepthVaryings i):SV_Target { return 0; }
            ENDHLSL
        }

        Pass
        {
            Name "DepthNormals"
            Tags { "LightMode"="DepthNormals" }
            ZWrite On ZTest LEqual Cull Back
            HLSLPROGRAM
            #pragma target 3.0
            #pragma vertex DepthNormalsVertex
            #pragma fragment DepthNormalsFragment
            #pragma multi_compile_instancing
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
            #include "BorderlandsToonModularLevelInput.hlsl"
            struct NormalAttributes { float4 positionOS:POSITION; float3 normalOS:NORMAL; UNITY_VERTEX_INPUT_INSTANCE_ID };
            struct NormalVaryings { float4 positionCS:SV_POSITION; half3 normalWS:TEXCOORD0; };
            NormalVaryings DepthNormalsVertex(NormalAttributes i)
            {
                UNITY_SETUP_INSTANCE_ID(i);
                NormalVaryings o;
                o.normalWS=TransformObjectToWorldNormal(i.normalOS);
                o.positionCS=TransformObjectToHClip(i.positionOS.xyz);
                return o;
            }
            // URP writes raw signed world normals into _CameraNormalsTexture (R8G8B8A8_SNorm).
            // Hidden/Custom/CartoonOutline reads that target through SampleSceneNormals, so
            // anything that packs to 0..1 here reads back at half sensitivity relative to every
            // stock Lit surface in the same frame.
            half4 DepthNormalsFragment(NormalVaryings i):SV_Target { return half4(normalize(i.normalWS),0); }
            ENDHLSL
        }
    }
    FallBack Off
}
