// Mobile environment shader for masks generated by Tools/Art/UV2 Ink Mask Baker.
// Base texture uses UV0; the ink mask and baked lightmap both use UV2/TEXCOORD1.
Shader "Project/Mobile Toon Environment UV2 Ink"
{
    Properties
    {
        [MainTexture] _BaseMap ("Base Map (UV0)", 2D) = "white" {}
        [MainColor] _BaseColor ("Base Color", Color) = (1, 1, 1, 1)

        [Header(Vertex Ambient Occlusion)]
        _AOColor ("AO Color", Color) = (0.25, 0.28, 0.35, 1)
        _AOStrength ("AO Strength", Range(0, 1)) = 0.45
        _AOContrast ("AO Contrast", Range(0.25, 4)) = 1

        [Header(Dark Fresnel)]
        _FresnelColor ("Fresnel Color", Color) = (0.03, 0.025, 0.04, 1)
        _FresnelStrength ("Fresnel Strength", Range(0, 1)) = 0.45
        _FresnelPower ("Fresnel Power", Range(0.5, 8)) = 3

        [Header(Height Fog)]
        _HeightFogColor ("Fog Color", Color) = (0.55, 0.62, 0.7, 1)
        _HeightFogTopY ("Fog Top Y", Float) = 0
        _HeightFogFalloff ("Fog Falloff", Float) = 4
        _HeightFogStrength ("Fog Strength", Range(0, 1)) = 0

        [Header(World Space Height Gradient)]
        _GradientBottomColor ("Bottom Color", Color) = (0.65, 0.72, 0.68, 1)
        _GradientTopColor ("Top Color", Color) = (1, 1, 1, 1)
        _GradientStartY ("Start Y", Float) = 0
        _GradientDistance ("Distance", Float) = 4
        _GradientStrength ("Strength", Range(0, 1)) = 1

        [Header(UV2 Ink)]
        [NoScaleOffset] _InkMask ("Ink Mask (UV2)", 2D) = "white" {}
        _InkColor ("Ink Color", Color) = (0.025, 0.02, 0.03, 1)
        _InkStrength ("Ink Strength", Range(0, 1)) = 1
        _InkOuterGlowStrength ("Outer Glow Black Multiply", Range(0, 1)) = 0.3

        [Header(Surface Edge Fade)]
        [NoScaleOffset] _SurfaceEdgeMask ("Surface Edge Mask (UV2)", 2D) = "white" {}
        _SurfaceEdgeColor ("Surface Edge Color", Color) = (0.22, 0.16, 0.10, 1)
        _SurfaceEdgeStrength ("Surface Edge Strength", Range(0, 1)) = 0

        [Header(Toon Lighting)]
        _ShadowTint ("Shadow Tint", Color) = (0.38, 0.42, 0.55, 1)
        _LightThreshold ("Light Threshold", Range(0, 1)) = 0.45
        _BandSoftness ("Band Softness", Range(0.001, 0.25)) = 0.04
        _BakedLightStrength ("Baked Light Strength", Range(0, 2)) = 1
    }

    SubShader
    {
        Tags
        {
            "RenderType" = "Opaque"
            "RenderPipeline" = "UniversalPipeline"
            "Queue" = "Geometry"
        }

        Pass
        {
            Name "ForwardLit"
            Tags { "LightMode" = "UniversalForward" }

            Cull Back
            ZWrite On

            HLSLPROGRAM
            #pragma target 2.0
            #pragma vertex Vert
            #pragma fragment Frag

            #pragma multi_compile _ _MAIN_LIGHT_SHADOWS
            #pragma multi_compile _ _MAIN_LIGHT_SHADOWS_CASCADE
            #pragma multi_compile _ _MAIN_LIGHT_SHADOWS_SCREEN
            #pragma multi_compile _ LIGHTMAP_ON
            #pragma multi_compile_fog
            #pragma multi_compile_instancing

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl"

            TEXTURE2D(_BaseMap);
            SAMPLER(sampler_BaseMap);
            TEXTURE2D(_InkMask);
            SAMPLER(sampler_InkMask);
            TEXTURE2D(_SurfaceEdgeMask);
            SAMPLER(sampler_SurfaceEdgeMask);

            CBUFFER_START(UnityPerMaterial)
                float4 _BaseMap_ST;
                half4 _BaseColor;
                half4 _AOColor;
                half4 _FresnelColor;
                half4 _HeightFogColor;
                half4 _GradientBottomColor;
                half4 _GradientTopColor;
                half4 _InkColor;
                half4 _SurfaceEdgeColor;
                half4 _ShadowTint;
                float _GradientStartY;
                float _GradientDistance;
                half _GradientStrength;
                half _AOStrength;
                half _AOContrast;
                half _FresnelStrength;
                half _FresnelPower;
                float _HeightFogTopY;
                float _HeightFogFalloff;
                half _HeightFogStrength;
                half _InkStrength;
                half _InkOuterGlowStrength;
                half _SurfaceEdgeStrength;
                half _LightThreshold;
                half _BandSoftness;
                half _BakedLightStrength;
            CBUFFER_END

            struct Attributes
            {
                float4 positionOS : POSITION;
                half3 normalOS : NORMAL;
                float2 uv0 : TEXCOORD0;
                float2 uv2 : TEXCOORD1;
                half4 color : COLOR;
                UNITY_VERTEX_INPUT_INSTANCE_ID
            };

            struct Varyings
            {
                float4 positionCS : SV_POSITION;
                float3 positionWS : TEXCOORD0;
                half3 normalWS : TEXCOORD1;
                float2 uv0 : TEXCOORD2;
                float2 uvInk : TEXCOORD3;
                half vertexAO : TEXCOORD6;
                DECLARE_LIGHTMAP_OR_SH(lightmapUV, vertexSH, 4);
                half fogFactor : TEXCOORD5;
                UNITY_VERTEX_INPUT_INSTANCE_ID
                UNITY_VERTEX_OUTPUT_STEREO
            };

            Varyings Vert(Attributes input)
            {
                Varyings output = (Varyings)0;
                UNITY_SETUP_INSTANCE_ID(input);
                UNITY_TRANSFER_INSTANCE_ID(input, output);
                UNITY_INITIALIZE_VERTEX_OUTPUT_STEREO(output);

                VertexPositionInputs positions = GetVertexPositionInputs(input.positionOS.xyz);
                VertexNormalInputs normals = GetVertexNormalInputs(input.normalOS);
                output.positionCS = positions.positionCS;
                output.positionWS = positions.positionWS;
                output.normalWS = normals.normalWS;
                output.uv0 = TRANSFORM_TEX(input.uv0, _BaseMap);
                output.uvInk = input.uv2;
                output.vertexAO = input.color.g;
                output.fogFactor = ComputeFogFactor(positions.positionCS.z);
                OUTPUT_LIGHTMAP_UV(input.uv2, unity_LightmapST, output.lightmapUV);
                OUTPUT_SH(output.normalWS, output.vertexSH);
                return output;
            }

            half4 Frag(Varyings input) : SV_Target
            {
                UNITY_SETUP_INSTANCE_ID(input);

                half3 normalWS = normalize(input.normalWS);
                half3 baseColor = SAMPLE_TEXTURE2D(_BaseMap, sampler_BaseMap, input.uv0).rgb * _BaseColor.rgb;
                half vertexAO = pow(saturate(input.vertexAO), max(_AOContrast, 0.01h));
                half3 aoTint = lerp(_AOColor.rgb, half3(1.0h, 1.0h, 1.0h), vertexAO);
                baseColor *= lerp(half3(1.0h, 1.0h, 1.0h), aoTint, _AOStrength);

                float gradientT = saturate(
                    (input.positionWS.y - _GradientStartY) / max(abs(_GradientDistance), 0.0001));
                half3 gradientColor = lerp(_GradientBottomColor.rgb, _GradientTopColor.rgb, gradientT);
                baseColor *= lerp(half3(1.0h, 1.0h, 1.0h), gradientColor, _GradientStrength);

                half surfaceEdgeMask = SAMPLE_TEXTURE2D(
                    _SurfaceEdgeMask, sampler_SurfaceEdgeMask, input.uvInk).r;
                half surfaceEdgeAmount = saturate((1.0h - surfaceEdgeMask) * _SurfaceEdgeStrength);
                baseColor = lerp(baseColor, _SurfaceEdgeColor.rgb, surfaceEdgeAmount);

                // The baker packs the solid core in red and its soft outer falloff in green.
                half2 inkMask = SAMPLE_TEXTURE2D(_InkMask, sampler_InkMask, input.uvInk).rg;
                half inkCore = saturate(1.0h - inkMask.r);
                half glowEnvelope = saturate(1.0h - inkMask.g);
                half outerGlow = saturate(glowEnvelope - inkCore);
                baseColor *= 1.0h - saturate(outerGlow * _InkOuterGlowStrength * _InkStrength);

                half inkAmount = saturate(inkCore * _InkStrength * _InkColor.a);
                baseColor = lerp(baseColor, _InkColor.rgb, inkAmount);

                half3 viewDirection = SafeNormalize(GetCameraPositionWS() - input.positionWS);
                half fresnel = pow(saturate(1.0h - abs(dot(normalWS, viewDirection))), max(_FresnelPower, 0.01h));
                baseColor = lerp(baseColor, _FresnelColor.rgb,
                    saturate(fresnel * _FresnelStrength * _FresnelColor.a));

                Light mainLight = GetMainLight(TransformWorldToShadowCoord(input.positionWS));
                half ndotl = saturate(dot(normalWS, mainLight.direction));
                half attenuation = mainLight.shadowAttenuation * mainLight.distanceAttenuation;
                half toonLight = smoothstep(
                    _LightThreshold - _BandSoftness,
                    _LightThreshold + _BandSoftness,
                    ndotl * attenuation);

                half3 directTint = lerp(_ShadowTint.rgb, mainLight.color, toonLight);
                half3 bakedGI = SAMPLE_GI(input.lightmapUV, input.vertexSH, normalWS);
                half3 color = baseColor * (directTint + bakedGI * _BakedLightStrength);
                half heightFog = saturate(
                    (_HeightFogTopY - input.positionWS.y) / max(abs(_HeightFogFalloff), 0.0001));
                heightFog *= saturate(_HeightFogStrength * _HeightFogColor.a);
                color = lerp(color, _HeightFogColor.rgb, heightFog);
                color = MixFog(color, input.fogFactor);
                return half4(color, 1.0h);
            }
            ENDHLSL
        }

        // Reuse URP's optimized opaque utility passes so the material casts shadows and
        // contributes depth/normals when those renderer features are enabled.
        UsePass "Universal Render Pipeline/Lit/ShadowCaster"
        UsePass "Universal Render Pipeline/Lit/DepthOnly"
        UsePass "Universal Render Pipeline/Lit/DepthNormals"
    }

    FallBack "Hidden/Universal Render Pipeline/FallbackError"
}
