namespace Quantum
{
    using System;
    using Photon.Deterministic;
    using UnityEngine;

    [Flags]
    public enum SkillActionPhase
    {
        Begin   = 1 << 0,
        OnGoing = 1 << 1,
        End     = 1 << 2
    }

    // Composable behavior mixed onto a SkillData via its Actions list - see SkillData. Phase is
    // configurable per asset instance and controls which lifecycle point(s) Execute fires at, so
    // "spawn on Begin" vs "spawn on End" is the same SpawnEntitySkillAction class with a different
    // Phase value, not two classes - retargeting when a behavior fires never needs new C#. Combine
    // flags (e.g. Begin | End) for an action whose single Execute call needs to run paired logic
    // at both ends - SkillSystem always invokes Execute with
    // exactly one bit set in firedPhase (never a combination), so Execute can branch on it safely.
    public abstract unsafe partial class SkillActionData : UpgradeData, IRankedUpgrade
    {
        // Icon/DisplayName/Rarity come from UpgradeData - lets this be offered directly as a
        // LevelUpPoolKind.SkillUpgrade card (see CharacterData.DashSkillUpgrades and HeroSkill's own
        // Actions, LevelUpUtility.AddHeroSkillUpgradeCandidates) without a separate wrapper type.
        // GetDescription() below reuses the existing
        // Description/DescriptionArgs machinery in SkillActionData.View.cs instead of a new field -
        // that machinery already supports live-templated values, which a plain static UpgradeData
        // field wouldn't.
        public override string GetDescription() => GetFormattedDescription();

        // Ranked ascensions author their per-rank flavor text directly here (rank 1 = index 0) - real
        // data, editable per-rank in the Inspector, rather than generated by string-interpolating the
        // tuned numbers in a GetDescription(int rank) override. Falls back to the templated
        // Description/DescriptionArgs above if empty/unauthored/out of range, so a non-ranked action
        // (MaxRank == 1) or one that hasn't authored per-rank text yet still works unchanged.
        [TextArea(2, 4)]
        public string[] RankDescriptions;

        // Shown on the level-up card for the specific rank being offered (see
        // GameplayUiController.BuildCardData). Virtual so a ranked action that genuinely needs
        // live-computed text (rather than authored data) can still override this directly.
        public virtual string GetDescription(int rank)
        {
            int index = rank - 1;

            if (RankDescriptions != null && index >= 0 && index < RankDescriptions.Length
                && string.IsNullOrEmpty(RankDescriptions[index]) == false)
                return RankDescriptions[index];

            return GetDescription();
        }

        // 1 (default) = classic single-pick, unchanged behavior for every existing SkillActionData
        // across every hero. >1 makes this a ranked Ascension line. Unlike PassiveUpgradeData, this
        // never changes SkillSlot.Upgrades' shape - a ranked action still occupies exactly one slot
        // entry; rank is a live lookup (SkillUpgradeUtility.GetRank) read fresh inside Execute below,
        // not baked at grant time. See SkillSystem.AddUpgrade/LevelUpUtility.AlreadyGranted for the
        // grant/eligibility side, and docs/level-up-upgrades.md for the full mechanism.
        //
        // An auto-property (not a plain field) specifically so this satisfies IRankedUpgrade.MaxRank
        // (a get-only interface property - a field can never implement an interface property member,
        // even though field/property access look identical at every call site). [field: SerializeField]
        // is what makes Unity still serialize/show it in the Inspector exactly like a plain field would.
        [field: SerializeField]
        public byte MaxRank { get; set; } = 1;

        // Ascending execution order within one phase - see SkillSystem.InvokeActions. Lower runs
        // first; every action defaults to 0, so leaving it alone reproduces plain list-order
        // execution. Set explicitly (e.g. a negative value) when an action's effect - like
        // IncreaseAreaSkillAction writing SkillSlot.AreaMultiplier - has to be visible to another
        // action already resolving the same phase, regardless of where either sits in the
        // Actions/Upgrades list.
        public int Priority = 0;

        public SkillActionPhase Phase = SkillActionPhase.Begin;

        // Paces an OnGoing action, which fires every tick otherwise. Zero or less means every tick;
        // the once-only phases ignore it.
        public FP Interval;

        // Lets a baseline SkillData.Actions entry be switched off without pulling it out of the list
        // or deleting the asset - flip this to rule one in or out while testing/balancing instead of
        // restructuring the list (and losing whatever else referenced this same asset instance).
        // Ignored for a slot->Upgrades grant (see SkillSystem.InvokeActions' ignoreActivated) - once
        // something explicitly grants this action to a player (e.g. a level-up pick), that grant is
        // itself the activation decision, so a shared asset toggled off for baseline use elsewhere
        // shouldn't silently no-op an upgrade a player was told they received.
        public bool Activated = true;

        // Read by SkillFxStep (see SkillActionData.View.cs) when a step's ScaleByRadius is on - lets
        // BeginFx/OnGoingFx/EndFx scale to match this action's own area without duplicating a Radius
        // field here for every action, most of which have no area at all. FP._1 (unscaled) by
        // default; override in a concrete subclass that already has its own Radius field, e.g.
        // `public override FP EffectRadius => Radius;`.
        public virtual FP EffectRadius => FP._1;

        // Generic prerequisite gate, checked by LevelUpUtility's candidate-collection methods
        // alongside the existing rank/already-granted filters - default true, so every existing
        // action across every hero is offered exactly as before. See PassiveUpgradeData.IsEligible's
        // own comment - same mechanism, same reusable intent, just the SkillActionData half.
        public virtual bool IsEligible(Frame f, EntityRef entity) => true;

        public abstract void Execute(Frame f, ref SkillSystem.Filter filter, SkillSlot* slot, SkillData skill, SkillActionPhase firedPhase);

        // Ranked actions override this instead of the parameterless Execute above - selfRef lets an
        // implementation look up its own live rank via SkillUpgradeUtility.GetRank(f, filter.Entity,
        // selfRef) without needing a separate identity-resolution mechanism. Default just forwards to
        // the parameterless overload, so every existing non-ranked SkillActionData subclass across
        // every hero compiles and behaves identically with zero changes.
        public virtual void Execute(Frame f, ref SkillSystem.Filter filter, SkillSlot* slot, SkillData skill,
            SkillActionPhase firedPhase, AssetRef<SkillActionData> selfRef)
            => Execute(f, ref filter, slot, skill, firedPhase);

        public bool ShouldExecute(Frame f, SkillSlot* slot, SkillActionPhase firedPhase, bool ignoreActivated = false)
        {
            if (Activated == false && ignoreActivated == false)
                return false;

            if ((Phase & firedPhase) == 0)
                return false;

            if (firedPhase == SkillActionPhase.OnGoing)
                return IsDueThisTick(f, slot);

            return true;
        }

        // Paced off the slot's own clock rather than a countdown stored here: actions are shared
        // assets with no per-entity state, and two actions on one skill have to be able to run
        // different intervals off the same activation. Crossing an interval boundary since last tick
        // is what fires it, so the cadence never drifts with DeltaTime. Overridable so a subclass can
        // pace off a different accumulator with the same trick - SpawnEntitySkillAction runs it off
        // distance travelled instead of time.
        protected virtual bool IsDueThisTick(Frame f, SkillSlot* slot)
        {
            if (Interval <= FP._0)
                return true;

            FP elapsed = slot->ActiveTime;

            return FPMath.FloorToInt(elapsed / Interval) > FPMath.FloorToInt((elapsed - f.DeltaTime) / Interval);
        }
    }
}
